### ISSUE TITLE
Add "Press & Hold" action when Shutdown

### ISSUE THREAD

**Issue by SunnyTiTi** [maforn/TimedShutdownAndroid#1]
On Infinix Phones, we need to long press (press and hold) about 5s to turn off phone.

![Infinix-Long-press-to-power-off](https://github.com/maforn/TimedShutdownAndroid/assets/6949265/9a36394c-cc73-4872-be20-ec72e07c479c)

**Comment by maforn** [comment]
Hi, I have just pushed the new version that should have what you are looking for. As soon as google accepts my update it will be published on the Play Store as well.
Keep me updated if it does or doesn't work as requested.

**Comment by SunnyTiTi** [comment]
Hi, Thank you very much. I will try and let you know if it works.

**Comment by SunnyTiTi** [comment]
It works very well on my Infinix phone.
