### ISSUE TITLE
Precision when asking for permissions

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#11]
When asking for permissions, the app only asks the user to grant them " in the parameters" or "restricted parameters". This is a bit confusing as a user might mistake it for the app parameters.

To be perfectly clear, ask about giving these permissions "in the [restricted] parameters of your device".

**Comment by Cwpute** [comment]
Same goes for Battery Optimization messages.

**Comment by maforn** [comment]
Done, now you just have to wait for the update to be published
