### ISSUE TITLE
Flip Phones

### ISSUE THREAD

**Issue by Oddone88** [maforn/TimedShutdownAndroid#14]
What about Options for Flip phones like Samsung Galaxy Zflip 4 and Zflip 5 when phone is shut 

![THUMB_001_kv_galaxy_zflip4_color_combo_1p](https://github.com/maforn/TimedShutdownAndroid/assets/110629724/2ca58168-d24d-444f-8e56-f250b94e6367)

**Comment by maforn** [comment]
Hi @Oddone88, can you explain what is needed? I have no clue how the shutdown is different in flip phones. If it is necessary, can you share a video or a few screenshots on how to turn off a flip phone?

**Comment by maforn** [comment]
Stale issue, not receiving an answer
