### ISSUE TITLE
Automatization integration 

### ISSUE THREAD

**Issue by Raffaele-dot** [maforn/TimedShutdownAndroid#15]
Hi, would you consider to create a way that allows another app (eg. Tasker) to send an input and trigger the power off task? It would be very useful if in Tasker it can be determined a trigger such as the period of inactivity of the device and your app will power it off, all without rooting permissions.

**Comment by maforn** [comment]
Hi @Raffaele-dot, I could allow access to the service, but frankly, I don't know how Tasker adds API to the app itself. Furthermore, I can't allow free access from everyone, otherwise an ill-intentioned individualcould use the service to shutdown your phone.

**Comment by rudolfmu** [comment]
I would also like to powerdown immediatly by another app that receives an SMS for the case of my phone being lost or stolen.
1. You could add a setting to shut down without further action. With a big warning. Then the user can use your App as a panic button or with Tasker etc. The setting would be resettable by deleting your apps data.
2. Include and export an extra activity to power down immediately, then this could be used. But more work for you and me.

I would like to have this option. Whoever else has my phone can shut it down anyway by pressing the button. I see no danger.

**Comment by maforn** [comment]
I'll look into it when I have time, I am quite busy right now. I'll be back in about a month or so if it is not really urgent

**Comment by Raffaele-dot** [comment]
Honestly the solution proposed at point 1 by @rudolfmu sounds easier to be applied by the end user. Not really sure how much development would save to reset the settings by deleting app data instaed of having a toggle tho

**Comment by ande-design** [comment]
This is a great little app & something I needed when using my iPod Classic. I now use this on my Walkman NW-A105. Having the ability to have a shut off time for bedtime snooze listening is so user friendly it makes me wonder why Apple had no concept of it.
I would like to ask for an additional feature however. As I invariably wake up during the night I like to just turn on what I was listening to & have it automatically go off again at a default time, without having to look at a screen or concentrate on options or setting a time, would be really good. Waking up & concentrating can lead to returning to full consciousness. So an autostart feature to use a default time would be so useful for device that is notable for poor battery usage.

I also think there needs to be better written guidance for users in setting up the app. I found it quite a bit confusing in understanding how to place the numbers that are for user inputs. I am a UX designer by trade & I can't help myself in looking out for others who would find it difficult to understand the tasks associated with the instructions.

I hope this helps.

**Comment by maforn** [comment]
Thank you @rudolfmu for your suggestion, I've implemented the change and I will soon push it to production

**Comment by maforn** [comment]
I've included an exported activity that you can call with an automation app, there are instructions on the info tab as well
