### ISSUE TITLE
Auto start - Auto set

### ISSUE THREAD

**Issue by ande-design** [maforn/TimedShutdownAndroid#17]
I have decided to put this here instead of at the end of another thread.

This is a great little app & something I needed when using my iPod Classic. I now use this on my Walkman NW-A105. Having the ability to have a shut off time for bedtime snooze listening is so user friendly it makes me wonder why Apple had no concept of it.
Apple gives you the ability to set a timer for auto shut off but you HAVE to set it every time. I have had my battery drain because the iPod just carried on for hours & hours without being shut off sometimes without me even listening to it.

As I invariably wake up during the night I like to just turn on what I was listening to & have it automatically go off again at a default time, without having to look at a screen or concentrate on options or setting a time, would be really good. Waking up & concentrating and looking at a bright screen can lead to returning to full consciousness. So an autostart feature to use a default shut off time would be so useful for device that is notable for poor battery usage.

I'm sure this could be easily adopted. By setting in a default delay to the setting it would allow a fix to the problem of someone accidently setting the default shut off at 1 second.

**Comment by maforn** [comment]
Hello ande, why can't you use a scheduled power off? As you have seen the app is extremely basic, even the UI is quite rough and the auto timer start would be difficult to place somewhere

**Comment by maforn** [comment]
In case the previous option is not what you need you can use Tasker, Automate or any other automation app to get the same result.

**Comment by ande-design** [comment]
I had assumed that it would be in the settings area. A tickbox that has a default time associated with it. This would be a toggle that would remain set after shutdown. 
I am currently assessing how your UX works. I think your settings should involve sub sections with guidance notes & an area where you can set defaults. 
In answer to your question, I like the simplicity of your app. I am not an Android power user & I am trying to force my Sony NW-A105 into being more battery friendly without rooting it.

**Comment by maforn** [comment]
I understand your points and think that the UI/UX would probably need a re-haul, the point is that it would require quite a lot of work for something that is already working decently.
