### ISSUE TITLE
Compatibility with tablets 

### ISSUE THREAD

**Issue by Raffaele-dot** [maforn/TimedShutdownAndroid#18]
Hi,  would it be possible to have this app also for tablet?

P.s: great job with the automation activity! I ended up using Automate instead of Tasker because the latter does not find the activity. With Automate works like a charm,  thank you!

**Comment by maforn** [comment]
Hello Raffaele, I'm glad the automation works well enough, even though I don't know why it is not working with Tasker. On my device, at least it works 🤷.
About the tablet version: the main problem is how to structure the ux when changing from horizontal to vertical and so on. I could try to force an always vertical, but I'm not sure whether it would work. Maybe I can open a channel for beta testing and add you to it so we can check. I'll look into it.

**Comment by Raffaele-dot** [comment]
"Dear Maforn, I've installed the app on the Samsung A8 tablet, and in portrait mode, it runs smoothly. I've also adjusted the buttons to accommodate horizontal orientation, which worked well too. However l, switching from vertical to horizontal it does not work as you have expected.

Regarding automation, I can confirm the app works with Tasker. The issue was that I didn't know how to view the list of activities in Tasker. However, when running the app with the lock screen on, I noticed it calls the power button, but no further inputs occur (simulated touches on the screen don't happen). Is it possible to emulate touch on the lock screen?"

**Comment by rudolfmu** [comment]
@maforn 
Your main activity has "Orientation: Sensor portrait", the automation activity has "Orientation: Unspecified". Automation should also be set to portrait.

The "tablet problem" also exists for phones. Make a shortcut with the app Activity Launcher, start the shutdown and flip the phone to horizontal. Then shutdown won't work as the menu layout changes.
