### ISSUE TITLE
single tap shows long press menu

### ISSUE THREAD

**Issue by danielskapunk** [maforn/TimedShutdownAndroid#21]
I'm using lineage 21, Android 14
When the timer runs out, the single tap in the power button seems to be too long and it displays the long press menu instead of powering off the device.

**Comment by maforn** [comment]
Hi @danielskapunk, at the moment the waiting time is 400ms. I can reduce it to 200ms, do you think that is enough?

**Comment by maforn** [comment]
I've pushed the version with 200ms, try it out when it is realeased on the play store and let me know.

**Comment by maforn** [comment]
As you are not answering anymore I suppose it works.
