### ISSUE TITLE
Doesn't work when screen is off

### ISSUE THREAD

**Issue by cousegit** [maforn/TimedShutdownAndroid#22]
When I set a schedule for example and my phone screen turns off after awhile as I fall asleep, the app won't do the actions in the background. Is it possible to add a command that the screen turns on as soon as the shutdown process starts? And is this also possible on the lock screen, so I don't have to unlock first?

**Comment by maforn** [comment]
Hi cousegit, your question is taking me by surprise, as the app should theoretically do both the things you asked. On my devices, it turns on the screen and it works when the phone is locked. Are you sure you gave the app all the permissions it needed, especially the ones about battery optimization?

**Comment by cousegit** [comment]
Yes, I definitely gave the app all the permissions it asked for at the start. I even tried multiple different settings and turned a few things off on my phone just to try make it work. But it almost never managed to turn my screen on automatically to start the shutdown process. I use a Samsung Galaxy A03. Are there any other settings I should change maybe?

**Comment by maforn** [comment]
I may have found the but, maybe it depends on your android version. In the [Accesibility Support Service](https://github.com/maforn/TimedShutdownAndroid/blob/master/app/src/main/java/com/maforn/timedshutdown/AccessibilitySupportService.java) the app requires the wake lock and forces the device awake with `ACQUIRE_CAUSES_WAKEUP `
`// set up wake lock
        PowerManager pm = (PowerManager) getApplicationContext().getSystemService(Context.POWER_SERVICE);
        PowerManager.WakeLock wakeLock = pm.newWakeLock(PowerManager.FULL_WAKE_LOCK | PowerManager.ACQUIRE_CAUSES_WAKEUP | PowerManager.ON_AFTER_RELEASE, "timed-shutdown:wl");
` 
Depending on your version ACQUIRE_CAUSES_WAKEUP may be deprecated. Can you tell me your Android version while I look for other ways to wake the screen up?

**Comment by maforn** [comment]
I have updated the code to work with the new versions of Android, now the bug should be fixed. In a few days Google Play Store and Fdroid should release the new version, let me know if it works.
