### ISSUE TITLE
[Feature Request] Ability to add multiple shortcuts (eg, to Reboot)

### ISSUE THREAD

**Issue by arijitroy454** [maforn/TimedShutdownAndroid#25]
Hello. I've been using this app for a while and it has been pretty good. I'm using this as an alternative to pressing the physical power button to shut down and reboot (so as to not wear the physical buttons down).

So you can say, i have been using this as a power menu replacement for my phone.

However, due to the app only allowing one shortcut at a time, i have to always manually drag the (1) shortcut in order to either do reboot or to shut down (as i cant have two shortcuts).

It would be a great addition to be able to have atleast two shortcuts at a time, and being able to pick in the timer menu to either reboot or shutdown.

**Comment by maforn** [comment]
Hi,
Thank you for your interest and for opening this issue. I understand your problem; maybe I could a "shortcuts" mini menu, even though the UI is already quite crowded. It does not make this much sense taking into account the purpose of this app, before editing I can suggest you try other apps such as [this app](https://play.google.com/store/apps/details?id=com.samiadom.Shutdown) that also call the power button and you can click whatever you want from there.

**Comment by arijitroy454** [comment]
Hello, thanks for your reply. Maybe it could be designed like this?

(the lines drawn is to highlight the shortcut that is currently selected)
![photo_2024-09-28_10-52-15](https://github.com/user-attachments/assets/218bae1a-39b6-4854-b5a9-c02238464f30)

The top large buttons can be "Shortcut 1" "Shortcut 2", and the bottom small button can be "save". From my understanding it does not make much sense to have more than two shortcuts, and so just having two seems enough.

About the app you linked, I have already seen it. The problem with such apps is that they will need to be given some sensitive permissions. And the app not even being open source brings with it a certain amount of risk, which i don't feel is worth taking.

There are quite a few similar apps on play store, and none of them are open source. On F-Droid all the apps seem to require root as they go about doing it in a complete different way.

There is a clear lack of an app to do what I mentioned (reboot/shutdown through software), let alone one that is open source.

No issues if it would be a hassle/not suit your goals. Your app is functional as is, and i understand if you are not interested. best regards.

**Comment by maforn** [comment]
The problem with your layout is that many phones have a shutdown sequence with a downward slide and the second dot must usually be aligned in the bottom half of the page, where you placed the buttons. I am considering adding a collapsable menu, maybe this can solve the problem. I'll let you know as soon as I try.

**Comment by arijitroy454** [comment]
Thats great to hear. Would be nice to have the added functionality. Thanks for considering it.

**Comment by maforn** [comment]
I've updated the app with the new quick configs buttons. Let me know if it's good enough for you.
