### ISSUE TITLE
Option to disable auto-shutdown if alarm is set afterwards

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#26]
My phone doesn't boot up in anticipation for an alarm to go off. So for example if i set my alarm to 8AM and i shut down my phone before going to sleep, the alarm is not going to ring.
I usually don't have an alarm set up, but when i do it's because i have something really important to do in the morning, so imagine my surprize the other day when i woke up like a flower, thinking i had all the tine in the world, but then realizing it just didn't ring because my phone was shut down by this app !
Of course this is the app working as intended, but since the app doesn't show it is currently running, i easily forgot it would shutdovn and leave me alarm-less.

To avoid other situations like that,  i'd like it the app to include an optional check before it shuts down, so that if there are any timers or alarms set up in the background for a time set after the shutdown, it cannot shutdown.

**Comment by maforn** [comment]
Hi again Cwpute,
Sadly what you asked is impossible because Android does not let me check another app's timers for privacy and security reasons. I can add maybe a permanent notification to let you know that your device will shut down at a specific time. What do you think about this?

**Comment by Cwpute** [comment]
It might do the trick yes... thanks !
Be sure to make it optional, i don't like apps that force permanent notifications, and i'm sure i'm not alone.

Le 20 octobre 2024 12:07:47 GMT+02:00, maforn ***@***.***> a écrit :

**Comment by maforn** [comment]
What do you think about this format?  
![p2](https://github.com/user-attachments/assets/d74a7100-c1d3-4f75-8b05-1dd4fff2c96a)
![p1](https://github.com/user-attachments/assets/2b75d530-be86-4726-853b-3671e06bd0d7)

**Comment by Cwpute** [comment]
Looks good ! is it a permanent notification ? as in: can it be dismissed or will it stay on ?
i suggest you make it so it can.t be dismissed.

**Comment by maforn** [comment]
I've added this in the last version that I've sent for review, when the app updates let me know if it's how you meant it

**Comment by Cwpute** [comment]
thanks i'll try it

**Comment by Cwpute** [comment]
it works ! thanks
