### ISSUE TITLE
Disable back button when power off dialog called

### ISSUE THREAD

**Issue by Zandut** [maforn/TimedShutdownAndroid#27]
Hi, can I disable back button when power off dialog called ? I want shutdown can be cancelled. Thank you, sorry my bad english :)

**Comment by Zandut** [comment]
sorry, I mean, cannot be cancelled :). I want the shutdown cannot be cancelled manually (when user pressed back button)

**Comment by maforn** [comment]
I could block the back button but all the others would still work. Also, I am not sure it's a good idea to prevent the shutdown to be cancelled, the user must always have a last choice

**Comment by Zandut** [comment]
can you help me ? :), I want to stop my child play the phone, he still can press the back button when dialog power off showed

**Comment by maforn** [comment]
I understand your problem, but blocking the entire screen is not feasible given how the app works. What I can suggest you is to use any other parental control app. There are many of them on the play store, such as [this one](https://play.google.com/store/apps/details?id=com.google.android.apps.kids.familylink), where you can setup a time limit for your child.
