### ISSUE TITLE
How to call Config 1 or 2 from Automate?

### ISSUE THREAD

**Issue by mikepiman** [maforn/TimedShutdownAndroid#28]
This a question, and also a bug report.

** My goal: is to use Automate to call either Config 1 or Config 2.

** Question:
I'm calling the Activity "com.maforn.timedshutdown. AutomationSupportActivity", (as indicated in the info tab), and it seems to run the last selected Config.  How would I specify which Config?
![Automate options](https://github.com/user-attachments/assets/bb7d87cf-4dd8-437f-8528-673f59f55e16)

** Maybe a bug:
I set each Config with a different "Initial general delay" so that I can tell which one is running, (with the toast message).

When Automate calls the above Activity and the last selected **Config was 1**, the Initial delay for Config 1 is displayed in the toast, but then the **click sequence for Config 2** runs, which seems incorrect.

When automate calls the above Activity and the last selected **Config was 2**, the Initial delay for Config 2 is displayed in the toast, and then the click sequence for Config 2 runs, which is expected.

~ ~ ~
Software: the latest Timed Shutdown (2.80) and Automate (1.44.2), on Android 13.

**Comment by maforn** [comment]
Hi,
Thank you for telling me about this. As of now, I am overwhelmed with university stuff and cannot look into it, but I'll check it at most at the end of November. It's a strange bug, and I'll have to check why it's doing something like that. I'll keep you posted about it. If you have a particular need to have it done before I'll try to look into it earlier.

**Comment by mikepiman** [comment]
Sure, take your time.  And being able to specify which Config to run (with two different Activities) would be great!

**Comment by maforn** [comment]
That's a great idea, I'll probably follow it

**Comment by maforn** [comment]
Hello, sorry if I took so much to check, but you are right, there was a bug in how the config were saved. I should have fixed it and now I'm working on making the different activities with widgets. In a few days I should be able to publish it to the play store.
Thank you for your patience

**Comment by maforn** [comment]
I've finished it and sent it for release both on FDroid and on the PlayStore. Let me know if it works or if there are any other problems

**Comment by mikepiman** [comment]
Thanks!  It sounds beautiful.  (I'm just using Automate directly now).

**Comment by maforn** [comment]
Now for Automate there are three activities: one that calls the last used in the app, one that calls the config 1 and one that calls the config 2. I hope that it will all work well and that you'll be satisfied :smiley:
