### ISSUE TITLE
Scheduling shutdown 

### ISSUE THREAD

**Issue by watermelondsugarlow** [maforn/TimedShutdownAndroid#3]
Hi everyone. A big thanks to those who made the app/edit it! I'd like to submit a request please. If possible, can you guys make the scheduling alarm style? By that I mean, can you make it so that at a set time on a set day(s) the device will be powered off: Ex. making it so that I can schedule a power off at 11pm everyday OR schedule a power off at 5am every Tuesday  

Thanks! All the best!

**Comment by maforn** [comment]
Hi watermelondsugarlow,
I'm glad you liked the app! You are not the first one to ask me to implement a shutdown schedule, but the difficulty is not low as it would require both dynamically adding alarms and managing boots timer. Also, this is a really expensive operation that uses a lot of battery and is discouraged by android's documentation. Furthermore, many phones already have this option in the settings, making it somehow redundant.
I'll try to implement it, but I can't promise anything.
You can obviously write me for any doubt, I'd happily answer you.

Cheers ^-^

**Comment by watermelondsugarlow** [comment]
Thank you for the response. I understand if it's not possible, I appreciate
all the effort! An old android phone of mine had that ability, but I
haven't seen that ability in any other phone since. I know a way to make
this possible is by rooting my phone, but that's not ideal so that is not
an option. So once again, if not possible, thanks a mil!

**Comment by maforn** [comment]
Hi @watermelondsugarlow,
I just pushed on google console the last update, it will be online in a few days I guess (maybe if you join the beta it will get there faster).
Please keep me updated on whether it's as you requested or not

**Comment by watermelondsugarlow** [comment]
Thank you so much! Delivered as requested. All the best.
