### ISSUE TITLE
12-hour time support for the time picker

### ISSUE THREAD

**Issue by alex391** [maforn/TimedShutdownAndroid#4]
I'm from the US and was confused by the time picker because it doesn't show AM or PM and I'm not used to 24-hour time. I figured it out pretty quickly but it would be good if 12-hour time was an option.

**Comment by maforn** [comment]
Hello @alex391,
I have just pushed on google console the new release, as soon as google releases it you'll find the option for 12 hours as requested (it can be changed on the settings tab).
I hope it's as you requested.
