### ISSUE TITLE
Inclusion in F-droid store

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#5]
Hello,
Would you consider publishing your app on the F-Droid store ? there are no similar app available on there and it would give more visibility and possible contributions to your work :)

Being published on the Google Play Store isn't helpful as yours is being drowned under a truckton of other shutdown apps claiming to do the same while providing ads-a-plenty to unwilling users.

**Comment by maforn** [comment]
Hi Cwpute, I'll try publishing it there as well. The process looks quite cumbersome, I'll do it when I have time
