### ISSUE TITLE
Alarms acting as timers ?

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#6]
First of all thank you soqmuch ! this app is a godsent. i've spent so much time searching for an app to do just that, without root!

My issue is as follows: i had set up an "Alarm" to `00:20`, hoping it would automatically shutdown my phone twenty minutes after midnight every day.
But what it actually seems to do is… shutdown ym phone *20 seconds* after the app started !! Which endelessly sfutdown the phone whenever i booted it up. Both funny and very problematic 🤡

Did i not understand how alarms worked, or may there be something messing with them?
One thing i can see could have altered this is that i previously tried a 1-second-long timer just to try the functionality of that app. Maybe it somehow automatically re-schedules that timer ?

**Comment by maforn** [comment]
Hello again Cwpute, thank you for your appreciation. This is a big problem and I did not even know it existed, I'll look into it asap. I have no clue why it would keep shutting down, the logic is based on the alarm schedule of the system, so it's really a strange problem the one that you are having

**Comment by maforn** [comment]
I think I found the problem, in the repeating alarms it set repeatings as the day of the current week, thus the system thought that they had already passed and decided to shut down the phone. I'll fix it in the next release

**Comment by maforn** [comment]
I have pushed the new update with this feature, as soon as Google will publish it you'll see it as well
