### ISSUE TITLE
Dialog window options

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#7]
![diulog options](https://github.com/maforn/TimedShutdownAndroid/assets/80604512/2382561a-e09b-49c2-b74e-6bddf64ed60c)

`Cancel` here acts as what you'd expect from the "Ok" button: it closes the window, but does not cancel anything !
Avoid any confusion and rename the Canced button to "Ok"

**Comment by maforn** [comment]
Thank you Cwpute, I'll change it soon
