### ISSUE TITLE
How to translate ?

### ISSUE THREAD

**Issue by Cwpute** [maforn/TimedShutdownAndroid#8]
Since the way this app works may be a bit unintuitive to some, it might help if we could translate it to our own languages.

How would you prefer receiving translation contributions, if any ?

I'd personally prefer going through platforms like Weblate or Crowdin, because i don't have an environment set up for pushing translation requests to this project (and i don't code).

**Comment by maforn** [comment]
Thank you for your suggestion, I've added Crowdin to the README
